# Copyright © Advanced Micro Devices, Inc., or its affiliates.
# SPDX-License-Identifier: MIT

[tox]
envlist = py38, py39, py310

[testenv]
deps =
    -r{toxinidir}/tox-requirements.txt
setenv =
    ROCM_PATH = {env:ROCM_PATH:/opt/rocm}
    CMAKE_CXX_COMPILER = {env:ROCM_PATH:/opt/rocm}/bin/amdclang++
commands =
    pip install --upgrade pip
    pip install .
    pytest test/
allowlist_externals =
    sh
